baseURL = 'https://zhubert.com/'
languageCode = 'en-us'
title = 'zhubert'

[[menus.main]]
name = 'Articles'
pageRef = '/articles'
weight = 10

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 20

[[menus.main]]
name = 'RSS'
url = '/index.xml'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
